#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Installing Powerswitch...\n"
sudo cp powerswitch.py /usr/local/bin/
sudo chmod +x /usr/local/bin/powerswitch.py

echo "=> Starting Powerswitch...\n"
sudo cp powerswitch.sh /etc/init.d/
sudo chmod +x /etc/init.d/powerswitch.sh

sudo update-rc.d powerswitch.sh defaults
sudo /etc/init.d/powerswitch.sh start

echo "Powerswitch installed.\n"
