#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Installing Power-switch...\n"
sudo cp power-switch.py /usr/local/bin/
sudo chmod +x /usr/local/bin/power-switch.py

echo "=> Starting Power-switch...\n"
sudo cp power-switch.sh /etc/init.d/
sudo chmod +x /etc/init.d/power-switch.sh

sudo update-rc.d power-switch.sh defaults
sudo /etc/init.d/power-switch.sh start

echo "Power-switch installed.\n"
