#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Stopping Powerswitch...\n"
sudo update-rc.d powerswitch.sh remove
sudo /etc/init.d/powerswitch.sh stop

echo "=> Removing Powerswitch...\n"
sudo rm -rf /usr/local/bin/powerswitch.py 
sudo rm -rf /etc/init.d/powerswitch.sh 

echo "Powerswitch uninstalled.\n"
