#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Stopping Power-switch...\n"
sudo update-rc.d power-switch.sh remove
sudo /etc/init.d/power-switch.sh stop

echo "=> Removing Power-switch...\n"
sudo rm -rf /usr/local/bin/power-switch.py 
sudo rm -rf /etc/init.d/power-switch.sh 

echo "Power-switch uninstalled.\n"
